### ISSUE TITLE
EPIC - Basic draft definition

### ISSUE THREAD

**Issue by tonofll** [tonofll/dramatize#3]
**Tasks**

- [ ] #1 
- [x] #2 
- [x] Integrate `PostgreSQL`
- [ ] Configure `deploy/docker` and docker compose to deploy all services

API development

- [ ] Install `sqlmodel` dependencies and `libpq-dev`
- [ ] Draft SQL basic model for MVP use case - make a rehearsal
- [ ]
